version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 300  # Threshold to 300 (tsx / react components)
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    threshold: 300  # Threshold to 300 (due to tsx / react components)
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 5 # in monorepo some files are often identical
  identical-code:
    config:
      threshold: 5 # in monorepo some files are often identical
exclude_patterns:
  - "**/node_modules/"
  - "**/config/"
  - "**/*.config.js"
  - "**/dist/"
  - "**/scripts/"
  - "**/__tests__/"
  - "**/*.test.js"
  - "**/*.test.jsx"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.d.ts"
  - "**/*.seed.ts"
  - "**/seed.ts"
