defaultSemverRangePrefix: ""

enableGlobalCache: false

nmMode: hardlinks-global

nodeLinker: node-modules

supportedArchitectures:
  os:
    - "current"
  cpu:
    - "current"

packageExtensions:
  apollo-server-micro@*:
    peerDependencies:
      graphql: ^15.6.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0-rc.1.cjs
