version: "3.8"

services:
  web-app-dev:
    # Service must be started explicitly with docker-compose up web-app
    profiles:
      - donotstart
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    stdin_open: true
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    container_name: web-app-dev
    volumes:
      - .:/app/
      # the volumes below prevents our host system's node_modules to be mounted
      - excl_node_modules_root:/app/node_modules/
      - excl_node_modules_web-app:/app/apps/web-app/node_modules/
      - excl_node_modules_blog-app:/app/apps/blog-app/node_modules/
      - excl_node_modules_core-lib:/app/packages/core-lib/node_modules/
      - excl_node_modules_db-main-prisma:/app/packages/db-main-prisma/node_modules/
      - excl_node_modules_ui-lib:/app/packages/ui-lib/node_modules/
      # the volume below prevents our host system's build to be mounted
      - excl_build_web-app:/app/apps/web-app/.next/
    depends_on:
      - main-db

  main-db:
    image: postgres:13-alpine
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    environment:
      - POSTGRES_DB=maindb
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_USER=nextjs
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      # you may use a bind-mounted host directory instead,
      # so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

volumes:
  excl_node_modules_root:
  excl_node_modules_web-app:
  excl_node_modules_blog-app:
  excl_node_modules_core-lib:
  excl_node_modules_db-main-prisma:
  excl_node_modules_ui-lib:
  excl_build_web-app:
  db_data:
