# Will be merged to root .ncyrc.yml.
# @link https://github.com/raineorshine/npm-check-updates

reject: [
    # prevent upgrade of package dependencies
    '@emotion/react',
    '@emotion/styled',
    'react',
    'react-dom',
    '@types/react',
    '@types/react-dom',
  ]
