name: CI-web-app-docker

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web-app/**'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '*.base.json'
      - '*.base.js'
      - '.prettier*.*'
      - '.github/workflows/**'
      - 'Dockerfile'
      - '*.Dockerfile'
      - 'docker-compose.yml'
      - 'docker-compose.*.yml'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    # Optional:
    #   Only consider those files/paths to trigger the github action
    #   to prevent unnecessary builds.
    paths:
      - 'apps/web-app/**'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '*.base.json'
      - '*.base.js'
      - '.prettier*.*'
      - '.github/workflows/**'
      - 'Dockerfile'
      - '*.Dockerfile'
      - 'docker-compose.yml'
      - 'docker-compose.*.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the web-app image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          file: ./Dockerfile
          tags: belgattitude/nextjs-monorepo-example-web-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      #- name: Build docker image
      #  working-directory: ./
      #  run: |
      #    docker-compose -f docker-compose.web-app.yml build --progress=plain runner
      #  env:
      #    DOCKER_BUILDKIT: 1
